import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home(props) {
  console.log(props.book)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
      <div className=' w-full md:w-2/3 lg:w-5/12  mx-auto sm:mx0 px-5 bg-bl'>

       <h1 className='font-bold '>SUMMARY</h1>

       {props.book.map(ob => ob.content ? <details className='p-2 w-full ' key={ob.header}>
        <summary className='pb-2'>
          {ob.header}
        </summary>
          <hr className='pb-3'></hr>
        <div className='text-sm whitespace-pre-line leading-snug '>

        {ob.content}
        </div>
       </details> : <h2 className='font-bold' >{ob.header}</h2> )}
      </div>
    </>
  )
}


import fsPromises from 'fs/promises';
import path from 'path'
export async function getStaticProps() {
  console.log('ciao')
  const filePath = path.join(process.cwd(), '/data/locke-raw.json');
  console.log(filePath)
  const jsonData = await fsPromises.readFile(filePath);
  const objectData = await JSON.parse(jsonData);
  return {
    props: {book: objectData}

  }
}
